Mutation:
    type: object
    config:
        fields:
            deleteVehicleMutation:
                type: ID!
                resolve: "@=mutation('delete_vehicle_mutation', [args['input']['id']])"
                args:
                    input:
                        type: IdInput!
            createCarMutation:
                type: Vehicle!
                resolve: "@=mutation('create_car_mutation', [args])"
                args:
                    input:
                        type: CarInput!
            updateCarMutation:
                type: Vehicle!
                resolve: "@=mutation('update_car_mutation', [args])"
                args:
                    input:
                        type: CarInput!