Mutation:
    type: object
    config:
        fields:
            DeleteCar:
                type: ID!
                resolve: "@=mutation('delete_vehicle', [args['input']['id']])"
                args:
                    input:
                        type: IdInput!
            DeleteTruck:
                type: ID!
                resolve: "@=mutation('delete_vehicle', [args['input']['id']])"
                args:
                    input:
                        type: IdInput!