Person:
    type: object
    config:
        description: "Person manage by the app"
        fields:
            id:
                type: "ID!"
                builder: "Relay::GlobalId"
                description: "Internal identifier"
            name:
                type: "String!"
                description: "Name of the person"
            title:
                type: "PersonTitle!"
                description: "Title of the person"
            birthDate:
                type: "BirthDate"
                description: "Birth date of the person"
            created_at:
                type: "DateTime!"
                description: "Date of creation of the person in database"
            vehicles:
                type: "[Vehicle]"
                description: "Vehicles of the person"
                args:
                    id:
                        description: 'Resolves vehicle using its id.'
                        type: 'String'
                resolve: "@=service('app.vehicles.resolver').resolveByPerson(value, idFromGlobalId(args['id']))"
            pet:
                type: "Animal"
                description: "Pet of the person"
