Person:
    type: object
    config:
        description: "Person manage by the app"
        fields:
            id:
                type: "ID!"
                builder: "Relay::GlobalId"
                description: "Internal identifier"
            name:
                type: "String!"
                description: "Name of the person"
            title:
                type: "PersonTitle!"
                description: "Title of the person"
            birthDate:
                type: "BirthDate"
                description: "Birth date of the person"
            createdAt:
                type: "DateTime!"
                description: "Date of creation of the person in database"
            vehicles:
                type: "[Vehicle]"
                description: "Vehicles of the person"
            pet:
                type: "Animal"
                description: "Pet of the person"
