Query:
    type: object
    config:
        fields:
            allPersons:
                type: '[Person]'
                args:
                    last:
                        description: 'Get X last elements of collection'
                        type: 'Int'
                resolve: "@=resolver('Persons', [args])"
            person:
                type: 'Person'
                args:
                    id:
                        description: 'Resolves person using its id.'
                        type: 'ID!'
                resolve: "@=resolver('Person', [idFromGlobalId(args['id'])])"
            vehicles:
                type: 'VehicleConnection'
                argsBuilder: "Relay::ForwardConnection"
                args:
                    owner:
                        description: 'Resolves vehicle using its owner id.'
                        type: 'ID'
                    id:
                        description: 'Resolves vehicle using its id.'
                        type: 'String'
                resolve: "@=resolver('Vehicles', [args])"
            vehicle:
                type: 'Vehicle'
                args:
                    id:
                        description: 'Resolves person using its id.'
                        type: 'ID!'
                resolve: "@=resolver('Vehicle', [idFromGlobalId(args['id'])])"