Vehicle:
    type: object
    config:
        description: "Vehicle"
        fields:
            id:
                type: "ID!"
                builder: "Relay::GlobalId"
                description: "The id of the vehicle"
            manufacturer:
                type: "String!"
                description: "The manufacturer of the vehicle"
            model:
                type: "String!"
                description: "The model of the vehicle"
            class:
                type: "String!"
                description: "Type of vehicle"
